# SPDX-FileCopyrightText: Copyright 2024 Prasad Tengse
# SPDX-License-Identifier: MIT
#
# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - "bot/dependabot"
      - "deps/actions"
    commit-message:
      prefix: "deps(actions):"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      actions:
        patterns:
          - "actions/*"
        exclude-patterns:
          - "actions/create-github-app-token"
      linters:
        patterns:
          - "golangci/golangci-lint-action"

  # For go, because of MVS, only security updates are relevant.
  # Ignore version updates as this package is a library.
  - package-ecosystem: gomod
    directory: /
    labels:
      - "bot/dependabot"
      - "deps/go"
    schedule:
      interval: "weekly"
      day: "saturday"
    commit-message:
      prefix: "deps(go):"
    pull-request-branch-name:
      separator: "-"
    # Disable version updates and only apply security updates.
    open-pull-requests-limit: 0
