# SPDX-FileCopyrightText: Copyright 2024 Prasad Tengse
# SPDX-License-Identifier: MIT

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: debug
on:
  workflow_dispatch:
    inputs:
      macos-version:
        type: choice
        description: 'Select macOS version'
        required: false
        default: macos-latest
        options:
          - macos-latest
          - macos-12
          - macos-13
          - macos-14

jobs:
  debug:
    permissions:
      contents: write
    runs-on: ${{ inputs.macos-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup vscode tunnel
        if: github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p .tunnel
          echo "Downloading VSCode CLI"
          curl -sSfL \
            --output .tunnel/vscode_cli.tar.gz \
            "https://code.visualstudio.com/sha/download?build=stable&os=cli-darwin-x64"

          echo "Unpacking VSCode CLI"
          tar --extract --file=.tunnel/vscode_cli.tar.gz --directory=.tunnel

          echo "Run Server"
          ./.tunnel/code tunnel --accept-server-license-terms --name go-launchd-debug
