# SPDX-FileCopyrightText: Copyright 2024 Prasad Tengse
# SPDX-License-Identifier: MIT

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: test
on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - stable
          - oldstable
          - 1.23.0-rc.1
        os:
          - macos-12
          - macos-13
          - macos-14
          - ubuntu-latest
          - windows-latest
        exclude:
          - os: windows-latest
            go: oldstable
          - os: windows-latest
            go: 1.23.0-rc.1
          - os: ubuntu-latest
            go: oldstable
          - os: ubuntu-latest
            go: 1.23.0-rc.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Test
        run: task --verbose test
        env:
          DEBUG: 1

      - name: Coverage View Percent
        run: go tool covdata percent -i .gocover

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.go }}
          path: .gocover
          retention-days: 30

  # Generate coverage profile from all coverage data.
  coverage:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Download and merge coverage data
        uses: actions/download-artifact@v4
        with:
          path: .gocover
          pattern: coverage-*
          merge-multiple: true

      - name: Coverage View Percent
        run: go tool covdata percent -i .gocover

      - name: Create Coverage Profile
        run: go tool covdata textfmt -i .gocover -o .gocover/coverage.out

      - name: View Coverage Profile
        run: go tool cover -func .gocover/coverage.out

      - name: Create Coverage Profile (HTML)
        run: go tool cover -html .gocover/coverage.out -o .gocover/coverage.html

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .gocover
          retention-days: 30
