# SPDX-FileCopyrightText: Copyright 2024 Prasad Tengse
# SPDX-License-Identifier: MIT

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: test
on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - stable
        os:
          - macos-11
          - macos-12
          - macos-13
          - macos-14
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Test
        run: task test

      - name: Coverage Create Profile
        # Do not use '-{flag}={arg}' format, as powershell mangles arguments with dots.
        run: go tool covdata textfmt -i .gocover -o .gocover/coverage.out

      - name: Coverage View Profile
        # Do not use '-{flag}={arg}' format, as powershell mangles arguments with dots.
        run: go tool cover -func .gocover/coverage.out

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --fail-fast --snapshot
