name: test
on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.21"
        os:
          - macos-11
          - macos-12
          - ubuntu-latest
        cgo:
          - "CGO_ENABLED=0"
          - "CGO_ENABLED=1"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Create Coverage data directory (Unix)
        if: runner.os != 'Windows'
        run: mkdir -p .gocover

      - name: Create Coverage data directory (Windows)
        if: runner.os == 'Windows'
        run: New-Item -ItemType Directory -Path .gocover

      - name: Test
        run: go test -v -cover -count=1 -cover -test.gocoverdir=.gocover ./...
        env:
          # https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions
          CGO_ENABLED: ${{ matrix.cgo == 'CGO_ENABLED=0' && '0' || '1' }}

      - name: Coverage Create Profile
        run: go tool covdata textfmt -i=.gocover -o .gocover/coverage.out

      - name: Coverage View Profile
        run: go tool cover -func .gocover/coverage.out
